name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'

template: |
  # What's Changed
  $CHANGES
categories:
  - title: ':rocket: Enhancement'
    labels:
      - enhancement
  - title: ':bug: Bug Fixes'
    labels:
      - bug
  - title: 'Configuration'
    labels:
      - configuration

version-resolver:
  minor:
    labels:
      - enhancement
  patch:
    labels:
      - bug

exclude-labels:
  - skip-changelog
  - release

commitish: main