name: Continuous Delivery for Staging

on:
  push:
    branches:
      - release/v**

jobs:
  cd:
    name: Continuous Delivery
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ '3.9' ]
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Get version
        id: get_version
        uses: battila7/get-version-action@v2
      - name: Build, tag, and push image to Docker Hub
        uses: docker/build-push-action@v3
        id: docker_build
        with:
          file: docker/Dockerfile
          push: true
          build-args: PYTHON_VERSION=${{ matrix.python-version }}
          tags: |
            loustler/python-skeleton:${{ steps.get_version.outputs.version }}
            loustler/python-skeleton:latest
          labels: |
            python_version=${{ matrix.python-version }}
          cache-from: type=gha
          cache-to: type=gha,mode=max