name: linter

on:
  push:
    branches:
      - main
    paths:
      - "**.go"
  pull_request:
    branches:
      - main
    paths:
      - "**.go"

jobs:
  linter:
    name: golangci-lint
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [ 1.18 ]
    steps:
      - uses: actions/checkout@v3

      # https://github.com/marketplace/actions/run-golangci-lint-with-reviewdog
      - name: golangci-lint
        uses: reviewdog/action-golangci-lint@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          tool_name: golangci-lint